del /q app\blogs\page.js
 del /q app\contact\page.js
 del /q app\direct-player\page.js
 del /q app\guest-speaking\page.js
 del /q app\login\page.js
 del /q app\minimal-player\page.js
 del /q app\privacy\page.js
 del /q app\providers.js
 del /q app\shop\page.js
 del /q app\sign-in\page.js
 del /q app\sign-up\page.js
 del /q app\signup\page.js
 del /q app\simple\page.js
 del /q app\simple-test\page.js
 del /q app\subscription\success\page.jsx
 del /q app\super-simple-test\page.js
 del /q app\terms\page.js
 del /q app\test\page.js
 del /q app\test-page\page.js
 del /q app\test-player\page.js
 del /q app\travel\page.js
 del /q app\view-avatars\page.js
 del /q lib\thumbnail-mapping.js
 del /q lib\utils.js
 del /q lib\video-catalog.js
 del /q lib\vimeo-browser.js
